### ISSUE TITLE
Error trying to use global variable from mounted app

### ISSUE THREAD

**Issue by morpheus65535** [bottlepy/bottle#1021]
I got a parent_app in a python file (parent.py) that I'm trying to mount in a child_app in another python file (child.py). The mount seems to work but, when I try to call a route from my parent_app trough the mount in my child_app, this route doesn't seems to be able to use global variable in my parent.py file.

The parent.py file:

    from bottle import route
    import bottle
    import subprocess as sp

    global extProc

    parent_app = bottle.Bottle()

    @parent_app.route('/start')
    def start_bazarr():
        global extProc
        extProc = sp.Popen(['python','child.py'])

    @parent_app.route('/stop')
    def stop_bazarr():
        sp.Popen.terminate(extProc)

    @parent_app.route('/restart')
    def restart_bazarr():
        stop_bazarr()
        start_bazarr()

    if __name__ == '__main__':
        start_bazarr()

The child.py file:

    from bottle import route, run
    import bottle
    from parent import parent_app

    child_app = bottle.Bottle()

    @child_app.route('/')
    def root():
        return u'Lorem Ipsum'

    if __name__ == '__main__':
        child_app.mount('/power', parent_app)
        child_app.run(host='127.0.0.1', port=8080)

The URL I'm trying to call:

`http://127.0.0.1:8080/power/restart`

The error I got:

Traceback (most recent call last):

    File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
        return route.call(**args)
    File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
        rv = callback(*a, **ka)
    File "C:\Users\morpheus\Desktop\parent.py", line 20, in restart_bazarr
        stop_bazarr()
    File "C:\Users\morpheus\Desktop\parent.py", line 16, in stop_bazarr
        sp.Popen.terminate(extProc)
    NameError: global name 'extProc' is not defined

What am I doing wrong?

**Comment by boumboum** [comment]
I've made a slight change in your code.
The main idea is: you don't know a priori how many times you have started a subprocess, so I've kept all the sp images in an array. So I do not have any error

`from bottle import route
import bottle
import subprocess as sp

extProc = []

parent_app = bottle.Bottle()

@parent_app.route('/start')
def start_bazarr():
    global extProc
    ep = sp.Popen(['python','child.py'])
    extProc.append(ep)

@parent_app.route('/stop')
def stop_bazarr():
    global extProc
    for ep in extProc:
        sp.Popen.terminate(ep)
    extProc = []

@parent_app.route('/restart')
def restart_bazarr():
    stop_bazarr()
    start_bazarr()

if __name__ == '__main__':
    start_bazarr()`

**Comment by morpheus65535** [comment]
Thank you for your input. It's a good idea but, unfortunatly, if I run the parent script and access http://localhost:8080/power/stop, it doesn't terminate the child subprocess. I can still load the root: http://localhost:8080. I'm still getting Lorem Ipsum.

Again, thanks for your help!

**Comment by morpheus65535** [comment]
@boumboum Have you been able to test it on your side?

**Comment by boumboum** [comment]
Well, you are right.
I do not have any error message (as was in your original message), but in fact the subprocess is not killed.
But this seems to be normal, as at the first time you execute parent.py, once your child process is created, immediately terminates. Therefore you lose all reference to extProc which is a local variable of parent.
You have to consider to create/declare extProc outside of parent which remains alive until all subprocesses are alive (either run a server in parent as well or serialize extProc (file, db, etc) and read and write its content at each start/stop.

This is just an idea...

**Comment by morpheus65535** [comment]
Ok, you're right, I didn't think about it but once child.py is started, parent.py exit because it's been coming to the end of the script. I've tried adding this to my __main__ but it makes no difference that I can see:

    while True:
        time.sleep(0.001)

Got another idea? I could run another server in parent.py as you have suggest but it would not serve any purpose other than keeping parent.py alive. I can get into trouble trying to use a port that is not available. Can I run a server without binding it to an ip/port?

**Comment by boumboum** [comment]
As I've told you the original parent.py is not the same as the the parent imported in child. Same name but different process (i.e. different variable). The imported parent is part of child (same process) not a different program/process.
Therefore even it it is alive because of your infinite while loop, it wont be called.
Parent has no webserver of its own, so you cannot call it.
Run a webserver in parent and you can call its routes.
Or you can use websocket to communicate between servers/processes

**Comment by boumboum** [comment]
You're welcome.
But don't forget: This is not a nice solution. You cannot run several server on the same port and if you are starting several child processes (via power/start) only one will service but the others will remain in memory.
So you should find an other (better) parent process management (maybe without any webserver) because anybody who knows the URL for starting or stopping a process can do that.
But this is up to you.

cheers
