### ISSUE TITLE
SimpleTemplateEngine block start and end cannot redefine

### ISSUE THREAD

**Issue by Jwink3101** [bottlepy/bottle#1022]
I am using a stripped out version of SImpleTemplateEngine for a project and ran into this issue. I thought maybe I introduced it in my changes, but it seems to exists in Bottle directly too.

You can redefine the SimpleTemplateEngine syntax and modify the `line_start`, the `inline_start` and the `inline_end`. However, for certain changes (though not *all*) changes to `block_start` and `block_end`, it fails.

Consider the following. In this, I change one type of syntax at a time. I also `reload` to make sure there isn't a cacheing issue.

```python
from imp import reload
import bottle

################
# Use reload to remove cache issues
reload(bottle)

default_txt = """\
<%
    A = 'hi'
%>
% B = 'bye'
{{A}} {{B}}
"""
out = bottle.template(default_txt)
assert out.strip() == 'hi bye'

################
# Use reload to remove cache issues
reload(bottle)
new_output = """\
<%
    A = 'hi'
%>
% B = 'bye'
[[A]] [[B]]
"""
out = bottle.template(new_output,
    template_settings=dict(syntax='<% %> % [[ ]]')
)
assert out.strip() == 'hi bye'

################
# Use reload to remove cache issues
reload(bottle)
new_line = """\
<%
    A = 'hi'
%>
! B = 'bye'
{{A}} {{B}}
"""
out = bottle.template(new_line,
    template_settings=dict(syntax='<% %> ! {{ }}')
)
assert out.strip() == 'hi bye'

################
# Use reload to remove cache issues
reload(bottle)
new_block = """\
[{
    A = 'hi'
}]
% B = 'bye'
{{A}} {{B}}
"""
out = bottle.template(new_block,
    template_settings=dict(syntax='[{ }] % {{ }}')
)
assert out.strip() == 'hi bye'
```

I get the following error (with personal info stripped out):

    Traceback (most recent call last):
      File "error_demo.py", line 59, in <module>
        template_settings=dict(syntax='[{ }] % {{ }}')
      File "[...]/python3.6/site-packages/bottle.py", line 3619, in template
        return TEMPLATES[tplid].render(kwargs)
      File "[...]/python3.6/site-packages/bottle.py", line 3409, in render
        self.execute(stdout, env)
      File "[...]/python3.6/site-packages/bottle.py", line 3396, in execute
        eval(self.co, env)
      File "[...]/python3.6/site-packages/bottle.py", line 189, in __get__
        value = obj.__dict__[self.func.__name__] = self.func(obj)
      File "[...]/python3.6/site-packages/bottle.py", line 3354, in co
        return compile(self.code, self.filename or '<string>', 'exec')
      File "<string>", line 3
        }]
        ^
    SyntaxError: invalid syntax

I am using python 3.6.3 in a virtualenv with nothing but bottle. Though I get the same issue in 2.7 (without the `from imp import reload`) line.

**Comment by Jwink3101** [comment]
ok...

I've been doing a lot of digging into the regex and I *think* it has to do with the regex block (3) and (4):

```regex
# 3: Open and close (4) grouping tokens
|([\[\{\(])
|([\]\}\)])
```

Using a block start and end with `{`, `[`, `(` at the **inner** character causes the error. For example, `{% %}` works (a la Jinja) but `%{ }%` will fail!

Assuming I am correct in my diagnosis, any ideas on a fix?

**Comment by Jwink3101** [comment]
The more I think about it the harder this becomes!. 

For example, if you use `[{ }]` as per my original post, it would be *really* hard to capture the following correctly:

```
[{
  settings_list = [{'a':1}]
}]
More text
[{
  # other code
}]
```

my understanding (which may be wrong) that the template splits at a wide range of possible tokens so it would be really hard to do a lookahead and there is no clear idea of greedy vs non-greedy in my above example (greedy would capture it *all* while non-greedy will leave the code too soon.

Maybe this should just be documented in the docs on limitations of block starts and ends.  (well, actually it should be documented in how to change them at all...)

**Comment by ProtonScott** [comment]
@Jwink3101 its all just regex underneath so you're running into token based limitations. From what I can tell, basically it can't match up the opening delimiter with the closing delimiter, so if you override the syntax manually by invoking the SimpleTemplate class and pass a different string to the syntax keyword argument it has to have matching delimiters. So to override `{{}}` you would need something like `%{}%` is my presumption. 

On using the brackets, I imagine the brackets are a very poor choice because they will get ate up by the python parser (if you ever used Mako templates, which from what I can tell SimpleTemplates seems to borrow heavy from in terms of implementation, you would have the same problem. I imagine thats why it does not allow you to change the syntax at all with its templates)

I've looked closely at lines 4020 through 4066 (at least on GitHub thats the line numbers that have the regex in question). What you would have to do is change the matching regex and the beginning and end ones.

I'm actually parsing through a lot of that right now, so if I come up some sweet solution I'll post it here, but effectively you need to re-write the `_re_token`, `_re_split`, and `_re_inl_` properties so they don't clobber each other, which they currently do now, if you change the syntax variables.

I would highly recommend not using `[{ }]` though, because the regex will eat it alive if you want to support Python constructs, because these symbols aren't parsed separately from what I can tell.

This is why Jinja2 uses `@contextfunctions` instead of allowing you to write pure python code in your templates (similar to SimpleTemplates or Mako). It reduces this complexity, but arguably makes it less powerful in an absolute sense.

Coming from Mako, I actually think that simpleTemplates gets the essence write. Perhaps it just needs some polish. I'm pretty decent with regular expressions so i'm gonna take a crack at this.
