### ISSUE TITLE
auth_basic and plugins

### ISSUE THREAD

**Issue by oz123** [bottlepy/bottle#1040]
Given a plugin that works like the SQLite plugin - that means it is activated if it sees the 'db' argument. the callback isn't going to work with auth_basic:

```
Traceback (most recent call last):
  File "./tiny/bottle.py", line 999, in _handle
    out = route.call(**args)
  File "./tiny/bottle.py", line 2000, in wrapper
    rv = callback(*a, **ka)
  File "/home/oznt/Software/tiny-cms/tiny/bottle.py", line 3155, in wrapper
    return func(*a, **ka)
TypeError: list_users() missing 1 required positional argument: 'db'
```

The code that created the crash is simple:

```                                                                                  
@app.route("/users/", method='GET')                                               
@auth_basic(User.verify_password)                                                 
def list_users(db):                                                               
                                                                                  
    users = User.select()                                                         
    # dictionaries are automatically converted to JSON                            
    return {"users": {user.name: user.email for user in users}}    
```

**Comment by oz123** [comment]
I have modified locally `auth_basic` to invoke the original callback with the arguments:

```
@@ -3145,12 +3147,14 @@ def auth_basic(check, realm="private", text="Access denied"):
 
         @functools.wraps(func)
         def wrapper(*a, **ka):
+            import inspect
+            callback_args = inspect.getfullargspec(func)
             user, password = request.auth or (None, None)
             if user is None or not check(user, password):
                 err = HTTPError(401, text)
                 err.add_header('WWW-Authenticate', 'Basic realm="%s"' % realm)
                 return err
-            return func(*a, **ka)
+            return func(*callback_args.args, **ka)
 
         return wrapper
```

This solves the issue, but I am not sure it covers all cases ... would you consider a PR for this?
