### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-142: ordinal not in range(128)

### ISSUE THREAD

**Issue by allbugsbelongtous** [bottlepy/bottle#1168]
I'm making a Bottle app and serving it with Gunicorn. I've been able to reduce the code to this demo snippet:

    demo.py
    ====================
    import bottle
    from bottle import get, redirect
    
    app = bottle.app()
    
    @get('/')
    def index():
        return redirect('/foobàr')

starting Gunicorn

    (venv) user@debian10:/srv/demo$ gunicorn --bind ":8080" demo:app
    [2019-10-09 12:32:35 +0200] [2614] [INFO] Starting gunicorn 19.9.0
    [2019-10-09 12:32:35 +0200] [2614] [INFO] Listening at: http://0.0.0.0:8080 (2614)
    [2019-10-09 12:32:35 +0200] [2614] [INFO] Using worker: sync
    [2019-10-09 12:32:35 +0200] [2617] [INFO] Booting worker with pid: 2617

when I visit `localhost:8080` I get a 500 with this error:

    [2019-10-09 12:32:36 +0200] [2617] [ERROR] Error handling request /
    Traceback (most recent call last):
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
        self.handle_request(listener, req, client, addr)
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 183, in handle_request
        resp.close()
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 409, in close
        self.send_headers()
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 329, in send_headers
        util.write(self.sock, util.to_bytestring(header_str, "ascii"))
      File "/srv/demo/venv/lib/python3.7/site-packages/gunicorn/util.py", line 507, in to_bytestring
        return value.encode(encoding)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 141-142: ordinal not in range(128)

The error **does not** show if I redirect to an ASCII URL, like `return redirect('/foobar')`. Only with non-ASCII URLs. To be honest, I'm not sure if this is a problem with Gunicorn or with Bottle.

**Comment by defnull** [comment]
Gunicorn is a little bit too struct here, but still right. Headers cannot contain characters outside of the ISO-8859-1 range (according to WSGI and HTTP spec) and the redirect target is written to the `Location` header.

**Comment by allbugsbelongtous** [comment]
crosslink: https://github.com/benoitc/gunicorn/issues/2127

**Comment by defnull** [comment]
Confirmed and fixed in gunicorn. Thanks
