### ISSUE TITLE
Exception in thread Thread-1 with Bottle v0.14-dev

### ISSUE THREAD

**Issue by FrViPofm** [bottlepy/bottle#1469]
Just launching Bottle app with 
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] on linux
```
Bottle v0.14-dev server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/vincent/Sites/local/Glassblower/lib/bottle.py", line 4000, in run
    path = getattr(module, '__file__') or ''
AttributeError: module 'sys' has no attribute '__file__'. Did you mean: '__name__'?
```

**Comment by defnull** [comment]
That line looks different in master, you probably have an old version? https://github.com/bottlepy/bottle/blob/master/bottle.py#L4001
