### ISSUE TITLE
Reloader bug

### ISSUE THREAD

**Issue by pevzi** [bottlepy/bottle#155]
Just noticed some strange things about reloader.
I have something like this in my code:

``` python
from bottle import run, route, static_file

@route('/test')
def test():
    return static_file('testfile', '.')

@route('/')
def index():
    return '<a href=test> Go to test </a>'

f = open('testfile', 'wb')
f.write('some text')
f.close()

run(reloader=True)
```

When I click on the link, then go back to main page and then modify my script, the reloader doesn't work properly and after the next request the traceback appears:

``` python
Exception happened during processing of request from ('127.0.0.1', 55094)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 639, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 116, in handle
    self.raw_requestline = self.rfile.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
```

After that reloader stops working at all unless you restart the server manually.

**Comment by reorx** [comment]
Hi all, I recently started using bottle, and also reproduced this bug in some simple situations.

My environment is:
- OS X El Capitan
- Python 2.7.10
- Bottle v0.12.9
- Chrome: Version 48.0.2547.0 canary (64-bit)

Using this simple pieces of code `bottleapp.py`:

```
#!/usr/bin/env python
# coding: utf-8

import bottle

@bottle.route('/')
def index():
    return '<h1> Hello </h1>'

bottle.run(host='localhost', port=8080, debug=False)
```

With steps as:
1. Run `bottleapp.py`, open http://127.0.0.1:8080/
2. Close the tab, then type `⌘ + shift + T` to re-open the tab
3. Hit Ctrl C in console.

Same output as @pevzi pasted just appeared. 

After searching and exploring the code, I started to realize this is not bottle's problem, but something related to socket and TCP connection. I tried to capture the TCP packet during the whole process with command `tcpdump -i lo0 tcp port 8080`, and found two things strange:

1. When refreshing the page, among those packets captured in the console, I found two FIN (flagged `[F]`) at the last few lines, that means the server immediately close the connection with Chrome after finishing the HTTP response. Note that normally when using `HTTP/1.1` and `Connection: keep-alive`, both server and Chrome won't close the TCP connection after HTTP request is finished, the two FIN should not appear in this situation.
2. When close and re-open the page, two SYN (flagged `[S]`) appeared in the console, but no HTTP request was logged, that means Chrome tried to reconnect with the server using TCP, but since there's a cache, it didn't send HTTP request to the server.

Those explained why the exception happened, because when Chrome reconnect with the server, it starts to handle the request, although no actual HTTP request is sent, the socket still halted with `recv` for the connection, so when we hit Ctrl C in console, `recv` is interrupted and the error occurs. And the reason this error mostly occurs in Chrome is because Chrome has the mechanism to reconnect before HTTP request is sent, IE seems don't have this.

So, by knowing what happened, we can exclude bottle from the suspects, it's either wsgiref's or HTTPServer/SocketServer's problem that does not provide the capability to keep the connection alive, and uglily waiting with `recv` on TCP connection established.

The code is not complicated, let's see what HTTPServer and wsgiref will do when handing the request:

https://github.com/python-git/python/blob/master/Lib/BaseHTTPServer.py#L325

You can see that the code of `BaseHTTPServer.py` is pretty and easy to understand, it won't close the connection and will continuously handling HTTP request in the same while True loop (which also means in one connection).

https://github.com/python-git/python/blob/master/Lib%2Fwsgiref%2Fsimple_server.py#L127

But `wsgiref` didn't do the same, although it inherits `BaseHTTPRequestHandler`, it override the `handle` method and make it unable to handle multiple request in the same connection. This stupid code is the key point, I was then convinced that wsgiref is the culprit to this problem.

I think it's unrealistic to wait for wsgiref to become better in the next version of Python 2.7, what we could  do to avoid this problem is to [switch to any backend other than wsgiref by default](http://bottlepy.org/docs/dev/deployment.html#switching-the-server-backend) even when we run bottle in development.

**Comment by legel** [comment]
I just experienced this baffling behavior on Python 2.7 running over Ubuntu... Indeed I was able to isolate down to issues with `wsgiref`.  Manually switching to another server (e.g. twisted) solved it for me: `run(host="0.0.0.0", port=8080, server='twisted')`.

Thanks to @reorx for pointing this out, and I'd definitely +1 his idea for switching the default backend away from `wsgiref`...  In the meantime hope this helps.

**Comment by caihengyou** [comment]
reorx solve my problem，thanks
