### ISSUE TITLE
Error handler crashes with redirect

### ISSUE THREAD

**Issue by iurisilvio** [bottlepy/bottle#236]
It happens because redirect exception is not handled by Bottle, because it already get an exception (404).

```
import bottle

@bottle.error(404)
def error_route(code):
    bottle.redirect('/')

bottle.debug(True)
bottle.run(reloader=True)
```

I get this exception:

```
<pre>HTTPResponse('HTTP Response 303',)</pre>
<h2>Traceback:</h2>
<pre>Traceback (most recent call last):
  File "/tmp/t/bottle.py", line 788, in wsgi
    out = self._cast(self._handle(environ), request, response)
  File "/tmp/t/bottle.py", line 741, in _cast
    out = self.error_handler.get(out.status, repr)(out)
  File "a.py", line 5, in error_route
    bottle.redirect('/')
  File "/tmp/t/bottle.py", line 1748, in redirect
    raise HTTPResponse("", status=code, header=dict(Location=location))
HTTPResponse: HTTP Response 303
</pre>
```

**Comment by lenormf** [comment]
Bump.
