### ISSUE TITLE
bottle silently merges responses / bottle is not reentrant

### ISSUE THREAD

**Issue by novas0x2a** [bottlepy/bottle#457]
Running this code should reproduce

```
#!/usr/bin/env python

from webtest import TestApp
from bottle import Bottle

Alpha = Bottle()
Bravo = Bottle()

TestAlpha = TestApp(Alpha)
TestBravo = TestApp(Bravo)

@Alpha.route('/')
def route1():
    return '12345%s' % TestBravo.get('/').body

@Bravo.route('/')
def route2():
    return '123'

# This blows up with
# AssertionError: Content-Length is different from actual app_iter length (3!=8)
# because the content-length from route2's response (len=3) is reused for the
# response to route1.
def main():
    print 'Alpha says %s' % TestAlpha.get('/').body

if __name__ == '__main__':
    main()
```

Full Backtrace:

```
Traceback (most recent call last):
  File "./bottle-response-bleed.py", line 28, in <module>
    main()
  File "./bottle-response-bleed.py", line 25, in main
    print 'Alpha says %s' % TestAlpha.get('/').body
  File "/home/mike/.virtualenvs/tmp/lib/python2.7/site-packages/webtest/app.py", line 759, in get
    expect_errors=expect_errors)
  File "/home/mike/.virtualenvs/tmp/lib/python2.7/site-packages/webtest/app.py", line 1109, in do_request
    res.body
  File "/home/mike/.virtualenvs/tmp/lib/python2.7/site-packages/webob/response.py", line 361, in _body__get
    % (self.content_length, len(body))
AssertionError: Content-Length is different from actual app_iter length (3!=8)
```

```
WebOb==1.2.3
WebTest==1.4.3
bottle==0.11.6
```

**Comment by cristicbz** [comment]
Still hitting this 3 years later. Did you ever find a workaround @novas0x2a ?

**Comment by novas0x2a** [comment]
I've been using this on every bottle app:
```python
    def wsgi(self, environ, start_response):
        try:
            old_dict = bottle._lctx.__dict__.copy()
            bottle._lctx.__dict__.clear()
            return super(App, self).wsgi(environ, start_response)
        finally:
            bottle._lctx.__dict__.clear()
            bottle._lctx.__dict__.update(old_dict)
```

However, this workaround no longer works as of 0.12, so I'm stuck on 0.11.7 until I port to a different framework.
