### ISSUE TITLE
Bottle (run and reloader true) + gevent Exception in thread Thread-1:

### ISSUE THREAD

**Issue by avelino** [bottlepy/bottle#600]
Is error?

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/python2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/avelino/.virtualenvs/mining/lib/python2.7/site-packages/bottle.py", line 3154, in run
    thread.interrupt_main()
KeyboardInterrupt
```

**Comment by ocean1** [comment]
could be this very same bug: https://github.com/abourget/gevent-socketio/issues/190
happens to me too.

**Comment by avelino** [comment]
https://github.com/bottlepy/bottle/issues/362
