### ISSUE TITLE
Testing Bottle application using webtest

### ISSUE THREAD

**Issue by mohierf** [bottlepy/bottle#789]
I tried to `unittest` a Bottle application with the webtest python suite. Based on the example provided in the doc, I built my own test module but I do not succeed in testing because I always get an 404 error on any page I try to request ...

Should you provide a working example of such testings ?

I copy my example: 
```
import os
import unittest

# for HTTP tests
from webtest import TestApp

from nose import with_setup # optional
from nose.tools import *

import bottle
from bottle import Bottle

class Server(Bottle):
    def __init__(self, host, port):
        Bottle.__init__(self)
        self._host = host
        self._port = port

    def set_routes(self):
        bottle.route("/")(self.index)
        bottle.route("/login", method="GET")(self.login_form)
        bottle.route("/login", method="POST")(self.login)
        bottle.route("/logout")(self.logout)

    def start(self):
        self._app.run(host=self._host, port=self._port)

    def index(self):
        return template('Hello {{name}}, how are you?', name='Guest')

    def login(self):
        username = bottle.request.POST.get('username', '').strip()
        password = bottle.request.POST.get('password', '').strip()
        bottle.redirect("/")

    def login_form(self):
        return 'Login form'

    def logout(self):
        return 'Bye'

server = Server(host='localhost', port=80)
server.set_routes()
# server.start()

# extend the class unittest.TestCase
class test_app(unittest.TestCase):
    def test_functional_login_logout(self):
        app = TestApp(server)

        app.post('/login', {'user': 'foo', 'pass': 'bar'}) # log in and get a cookie

        assert app.get('/admin').status == '200 OK'        # fetch a page successfully

        app.get('/logout')                                 # log out
        app.reset()                                        # drop the cookie

        # fetch the same page, unsuccessfully
        assert app.get('/admin').status == '401 Unauthorized'        
```

And the output of nosetests: 
```
$ nosetests -v -s test_bottle.py
test_functional_login_logout (test_bottle.test_app) ... ERROR

======================================================================
ERROR: test_functional_login_logout (test_bottle.test_app)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shinken/alignak-webui/test/test_bottle.py", line 73, in test_functional_login_logout
    app.post('/login', {'user': 'foo', 'pass': 'bar'}) # log in and get a cookie
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 370, in post
    content_type=content_type)
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 735, in _gen_request
    expect_errors=expect_errors)
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 631, in do_request
    self._check_status(status, res)
  File "/usr/local/lib/python2.7/dist-packages/webtest/app.py", line 663, in _check_status
    res)
AppError: Bad response: 404 Not Found (not 200 OK or 3xx redirect for http://localhost/login)

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 404 Not Found</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 404 Not Found</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost:80/login&#039;</tt>
               caused an error:</p>
            <pre>Not found: &#039;/login&#039;</pre>
        </body>
    </html>


----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)
```

**Comment by Dareen** [comment]
+1

**Comment by defnull** [comment]
class Server(Bottle):
        def set_routes(self):
            bottle.route("/")(self.index)
            bottle.route("/login", method="GET")(self.login_form)
            bottle.route("/login", method="POST")(self.login)
            bottle.route("/logout")(self.logout)

You should not subclass Bottle and if you do, you should install the routes to ``self`` and not the global default application.

        def start(self):
            self._app.run(host=self._host, port=self._port)

Where is ``_app`` coming from?

**Comment by Dareen** [comment]
in my server file:

```python
from bottle import Bottle

application = Bottle()

@application.route("/check")
def check():
    return "Up and running!"
```

in my test file:
```python
import httplib
import unittest

import webtest
from should_dsl import should
from nose.plugins.attrib import attr

from myservice.server import application


@attr("component_test")
class ServerComponentTests(unittest.TestCase):

    def test_health_check_should_return_OK(self):
        """ test health check endpoint should return OK"""
        app = webtest.TestApp(application)
        app.get(url="/health")
        response.status | should | equal_to(httplib.OK)
```

running `nosetests` yields the following:

```bash
E
======================================================================
ERROR: test health check endpoint should return OK
----------------------------------------------------------------------
Traceback (most recent call last):
  File "..../myservice_env/myservice/test/__init__.py", line 41, in test_health_check_should_return_OK
    app.get(url="/health")
  File "..../myservice_env/local/lib/python2.7/site-packages/webtest/app.py", line 323, in get
    expect_errors=expect_errors)
  File "..../myservice_env/local/lib/python2.7/site-packages/webtest/app.py", line 632, in do_request
    self._check_status(status, res)
  File "..../myservice_env/local/lib/python2.7/site-packages/webtest/app.py", line 664, in _check_status
    res)
AppError: Bad response: 404 Not Found (not 200 OK or 3xx redirect for http://localhost/health)

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 404 Not Found</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 404 Not Found</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost:80/health&#039;</tt>
               caused an error:</p>
            <pre>Not found: &#039;/health&#039;</pre>
        </body>
    </html>


----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)
```

**Comment by mohierf** [comment]
Thanks.

`_app` is a typo when I copied ... anyway, the start function is not called.

I followed your advice and changed my coding to avoid subclassing Bottle.
