### ISSUE TITLE
Is this an issue with Bottle and CGI

### ISSUE THREAD

**Issue by midunrajendranpandera** [bottlepy/bottle#836]
I am trying to use Python 3.4.3 and Bottle 0.12.8 to run a simple webservice using cgi. I am running the below script from my Linux system. I was able to run the the same service without CGI. 

---------------------------------------

import bottle
from bottle import route, run, request, response

host = 'XXXX'
port = '8080'
debug = 'False'

@route('/hello/',  method=['OPTIONS','GET'])
def hello():
    return("Success")

bottle.run(host=host, port=port,debug=debug,server='cgi')
#bottle.run(host=host, port=port,debug=debug)

---------------------------------------

I get the below error, when I run the service with CGI- 

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/bottle.py", line 858, in _handle
    route, args = self.router.match(environ)
  File "/usr/local/lib/python3.4/site-packages/bottle.py", line 413, in match
    verb = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
<h1>Critical error while processing request: </h1><h2>Error:</h2>
<pre>
KeyError(&#039;REQUEST_METHOD&#039;,)
</pre>
<h2>Traceback:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.4/site-packages/bottle.py&quot;, line 957, in wsgi
    or environ[&#039;REQUEST_METHOD&#039;] == &#039;HEAD&#039;:
KeyError: &#039;REQUEST_METHOD&#039;

</pre>
Status: 500 INTERNAL SERVER ERROR
Content-Type: text/html; charset=UTF-8
Content-Length: 374

<h1>Critical error while processing request: </h1><h2>Error:</h2>
<pre>
KeyError(&#039;REQUEST_METHOD&#039;,)
</pre>
<h2>Traceback:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.4/site-packages/bottle.py&quot;, line 957, in wsgi
    or environ[&#039;REQUEST_METHOD&#039;] == &#039;HEAD&#039;:
KeyError: &#039;REQUEST_METHOD&#039;

</pre>

--------
Am I doing something wrong here or is it a bug or non-compatibility between python and bottle version. Any pointers would help.
Thanks,

**Comment by jz4es** [comment]
I don't know. Have u figure it out. Same problem here

**Comment by defnull** [comment]
You cannot execute a CGI script directly. It has to be called by a CGI capable web server (e.g. Apache) that populates a lot of environment variables when calling it. One of them is `REQUEST_METHOD`.

Why do you want to use CGI in the first place?

**Comment by jz4es** [comment]
I want to set up bottle on IIS 8. Yet the idea seems ridiculous in the first place.

**Comment by defnull** [comment]
Looks like IIS supports WSGI directly: http://www.helicontech.com/articles/running-wsgi-on-iis/

**Comment by jz4es** [comment]
Cool stuff. I'll try it out and keep me updated if u succeeded!
