### ISSUE TITLE
POST forms type=float error

### ISSUE THREAD

**Issue by hoguera27** [bottlepy/bottle#847]
what is wrong get compra as float?

route("/new", method="POST")
def new_item():
    """
    Add a new item
    """
    descripcion = request.forms.get('descripcion')
    compra = request.forms.get('compra', type=float)
    venta = request.forms.get('venta')
    pesos = request.forms.get('pesos')
    proveedor = request.forms.get('proveedor')
    stock = request.forms.get('stock')

    pevendedor = float(compra)*1.15
    publico = float(compra)*1.27

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Library/Python/2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/hoguera/Documents/Bottle/bottle/Genesis/inicio_viejo.py", line 76, in new_item
    pevendedor = float(compra)*1.15
TypeError: float() argument must be a string or a number

**Comment by hoguera27** [comment]
problem solved, the problem was the name of the variable "compra" change for "compras"
