### ISSUE TITLE
Request/response timeout

### ISSUE THREAD

**Issue by kuraga** [bottlepy/bottle#909]
Good day!

How do I set a timeout for request? Seems like Bottle is blocked in read forever if needed:
```
 - - [02/Dec/2016 11:36:37] "GET http://httpheader.net/ HTTP/1.1" 404 765
^C----------------------------------------
Exception happened during processing of request from ('89.248.172.90', 57776)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 119, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
----------------------------------------
 - - [03/Dec/2016 01:18:59] code 400, message Bad request syntax ('\x05\x01\x00')
```

Thanks.

**Comment by defnull** [comment]
Do not use the development server for anything serious. It is single-threaded (to simplify debugging) and does not protect your from broken connections, slow clients or other client-side errors.

**Comment by kuraga** [comment]
@defnull thanks! "development server" == Bottle?

**Comment by defnull** [comment]
Bottle is a web framework, not a web server. It runs on any WSGI compatible web server out there. You can choose from a lot of options. https://bottlepy.org/docs/dev/deployment.html

**Comment by kuraga** [comment]
Oh, really, remember!  Bottle just integrates a server! Thanks.
