### ISSUE TITLE
Problems using 2 plugins that modify the arguments

### ISSUE THREAD

**Issue by kianxineki** [bottlepy/bottle#915]
I am creating a new plugin for bottle but I already had some assets in the project and I have encountered an error.

I put a sample code that reproduces the error

```python
from bottle import install, run, get
from functools import wraps
import inspect


class CerberusPlugin(object):
    name = 'CerberusPlugin'
    api = 2
    keyword = 'schema'

    def apply(self, callback, route):
        schema = route.config.get(self.keyword, None)
        if not schema:
            return route.callback

        @wraps(callback)
        def wrapper(*args, **kwargs):
            if inspect.signature(callback).parameters.get(self.keyword):
                kwargs[self.keyword] = schema
            # TODO: functionality not implemented
            return route.callback(*args, **kwargs)
        return wrapper


class CerberusPlugin2(object):
    name = 'CerberusPlugin2'
    api = 2
    keyword = 'schema2'

    def apply(self, callback, route):
        schema = route.config.get(self.keyword, None)
        if not schema:
            return route.callback

        @wraps(callback)
        def wrapper(*args, **kwargs):
            if inspect.signature(callback).parameters.get(self.keyword):
                kwargs[self.keyword] = schema
            # TODO: functionality not implemented
            return route.callback(*args, **kwargs)
        return wrapper



install(CerberusPlugin())
install(CerberusPlugin2())

@get('/cerberus', schema={'test': {'type': 'string'}})
def test_cerberus(schema):
    print(schema)
    return "guay"

run()
```

error:
``` python
Bottle v0.12.11 server starting up (using WSGIRefServer())...
Listening on http://127.0.0.1:8080/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
TypeError: test_cerberus() missing 1 required positional argument: 'schema'
127.0.0.1 - - [29/Dec/2016 18:32:58] "GET /cerberus HTTP/1.1" 500 749
```

 if I do not install the plugin "CerberusPlugin" works correctly

bottle version: 0.12.11

I am doing something wrong? Thank you!

**Comment by kianxineki** [comment]
I did not realize that callback and route.callback are not the same! route.callback is the original and callback is the callback of the previous plugin.

Https://github.com/bottlepy/bottle/blob/master/bottle.py#L567

**Comment by defnull** [comment]
Yes, thats true. It is documented here: https://bottlepy.org/docs/dev/plugindev.html#the-route-context

**Comment by kianxineki** [comment]
@defnull 
Yes, I found it by reading that part of the documentation! Thank you!

I would like to make other inquiries about bottlepy but I do not know if creating an issue is the right way. Thank you!
